### ISSUE TITLE
Alterations for DOTS support, almost working

### ISSUE THREAD

**Issue by MostHated** [jinsek/MightyTerrainMesh#7]
I am sorry to bother you again, but I had hopefully one last question.

 Bearing in mind I know essentially nothing about shaders, I was able to get the MTTerrainLit shader to render within a DOTS SubScene (the newer/current Entities.Graphics package) , but I can't seem to get the additional "MTTerrainLitAdd" shader to work along with it, which seems to be blending additional textures into the mesh. In the example I was testing, there are dark spots where rock texture typically would be. (Seen in the images below)

I had to make adjustments, such as:

```hlsl
# File - MTTerrainLit.shader

#pragma target 4.5
#pragma multi_compile _ DOTS_INSTANCING_ON
# ^ These changes I had to make in a few files
```

```hlsl
#File - MTTerrainLitInput.hlsl

# Had to change this CBUFFER_START(Terrain) to the following:
CBUFFER_START(UnityPerMaterial)
```
Then I had to comment out a few things having to do with TerrainArray to get rid of some errors, but upon doing so, rendering worked in Entities.Graphics/SubScenes, seemingly properly to my extreme surprise, minus that one thing with the TerrainLitAdd not rendering. 

I have a feeling that it is either something very easy, or something very difficult that would require much more knowledge than I have in shaders to fix. I feel that I simply got lucky that the changes I made worked at all, and there are probably bigger implications, but I am wondering if you happen to know of something off the top of your head that might be causing this behavior? 

If not, I completely understand. It was a long shot to begin with on my part. I really just wanted to see if it would be done in the first place since Entities.Graphics doesn't yet have native terrain rendering capability. I have been looking for some sort of working mesh conversion, and this was the closest I have gotten/found.

<details>
<summary>Original</summary>

![](https://img.instance.id/ZMf96S3WqnvG/direct)

</details>

<details>
<summary>Exported mesh within SubScene</summary>

![](https://img.instance.id/VIV3MRWp8dXz/direct)

</details>

Thanks,
-MH

**Comment by jinsek** [comment]
Hi, MH
The TerrainLit.shader came from unity offical URP Terrain shader, which I just modified a little to fit my file serialization, it uses the same resources with official shader, so, I think it's a better way for your requirements to find the offcial terrain shader of your render pipeline, and tweak it to fit your needs. hope this helps! have fun there!
