### ISSUE TITLE
How can i use MeshCreator?

### ISSUE THREAD

**Issue by dklee98** [jinsek/MightyTerrainMesh#8]
Hi, I am a very beginner to unity, so i am slightly confused about using your great plugin.
in readme, instruction 1. click MightTerrainMesh->MeshCreator open the mesh editor interface.
Q: where are MeightTerrainMesh and MeshCreator button??
I tried really hard to find that button or its role, but I just can't find it.
i uploaded my view of the unity in linux, i clone your project to the unity folder, and only open the TerrainDemo scene.

please help me.. thankyou

![image](https://github.com/jinsek/MightyTerrainMesh/assets/55484370/30a032e8-f581-475d-a478-c32d867306f7)

**Comment by jinsek** [comment]
Hi Dongkyu, did u see the red error messages at the left bottom column? I believe that there are some c# script compile errors in your project, I had never tested for the linux version, so I'm afraid that you have to check it out by yourself. 
The Mesh Creator part is simple, main function entrance locates in 
https://github.com/jinsek/MightyTerrainMesh/blob/master/Assets/MightyTerrainMesh/Editor/MTMeshEditor.cs
this file.
Once your project resovled all the compile errors , the MightTerrainMesh command bar will appear on the top menu, before the help button I think^^
If you got some shader compile error, you can just leave them for now, focus on those c# complie errors first.
Mesh Creator did nothing but samples the terrain heights and builded a mesh. 
Hope this helps~

**Comment by dklee98** [comment]
Thank you for your fast and kind answer!!
I solved my problem using Windows Unity and the appropriate version 21.2.6f1 as you recommended.
MightyTerrainMesh button appears and it works!

thank you again:)
